### ISSUE TITLE
Integrate with Gnome date/time widget

### ISSUE THREAD

**Issue by szpak** [vancha/gnomeShellBinaryClock#1]
First of all thanks for making that extension! In the past I had been using that [one](https://extensions.gnome.org/extension/46/binary-clock/), but it is no longer [maintained](https://github.com/azdyb/gnome-shell-extension-binaryclock).

I wonder if it would be possible to (optionally) integrate it with the main date/time widget in Gnome (as shown [here](https://extensions.gnome.org/extension/46/binary-clock/))? To replace the original time and/or to make it linked to the drop down menu which is installed. The reason it that I would like to disable the original time displaying, but on the other hang it is useful to press Super+M (or just click the time to see a calendar and notifications).

**Comment by vancha** [comment]
Thank you for opening this issue, I' ll look into how that would be possible. If i found out how I'll update this page.

**Comment by vancha** [comment]
![plugin](https://user-images.githubusercontent.com/9658702/72208917-01a61380-34a9-11ea-9a01-28b14105998e.png)
Do you mean something like this? If so i can update the plugin and that will be the new layout.

**Comment by szpak** [comment]
Exactly! I assume that I can still click "the clock" to see system notifications and the calendar (with a click or Meta-M), right?

As they may be people with different preferences/expectations, if it is not a big problem (from the code point of you), I would propose to have a configuration switch to change between modes (with the new one as default).

Btw, before updating plugin in The extension portal, you might push changes (to master or to some other branch) to allow me to play with it and report potential remarks and/or spotted problems.

**Comment by vancha** [comment]
Sure thing 😁 expect the commit tomorrow, since I was 99% asleep ^^

**Comment by vancha** [comment]
hmm I hope this improves things, but before I can actually commit the changes to the gnome shell extension site i really need to improve the quality of this code. If there's anything you like changed please let me know :)

**Comment by szpak** [comment]
It works without any problem, nice.

Some suggestions:
1. Before you got fluent with the binary time format it might be useful to display time in the original decimal format once drop down menu (with events and calendar) is shown - the same as in the aforementioned [implementation](https://extensions.gnome.org/extension-data/screenshots/screenshot_46_1.png) (if it's easy to implement).
2. I see the following warning in code:
> gnome-shell[3040]: JS WARNING: [.../gnome-shell/extensions/binaryclock@vancha.march/extension.js 221]: assignment to undeclared variable testlabel

3. It's JavaScript, but probably some code formatting and general improving could be useful ;).

I will play with it more and maybe some other ideas will come up :).

**Comment by vancha** [comment]
that'd be great ^^ I'm trying to implement a list of settings (like the ones you seen with extensions in gnome tweaks that support it), where you can add/remove such a second clock (and maybe even change it's location. Now only the clock shows up, but I would personally want the current date there as well, this could also be a setting. If you think of anything you'd like changed, please open a new issue, so this one can be closed.
thanks again :)
