### ISSUE TITLE
Seconds not updating

### ISSUE THREAD

**Issue by techonerd** [vancha/gnomeShellBinaryClock#2]
Seconds are not updating frequently and correctly on gnome-shell-version=3.34.4

**Comment by vancha** [comment]
Hey there! thanks for submitting this issue :) There is currently a new version of the plugin awaiting moderating on the gnome shell extensions site. Version three only shows the seconds when you have seconds enabled in your clock, and omits the last two columns if you have them disabled. 
![clock](https://user-images.githubusercontent.com/9658702/77521638-4aa01e00-6e83-11ea-9755-335cee88abd0.png)
To enable or disable seconds in the gnome shell clock, you can type the following in your terminal: 
gsettings set org.gnome.desktop.interface clock-show-seconds true
to update the plugin, refresh gnome shell with alt+f2 (then type the letter "r" in the prompt, and press enter).
This only works in version three which is, as mentioned, still pending review. I hope this solves the issue for you :)

**Comment by vancha** [comment]
The changes for this extensions are no longer awaiting moderation, and have been included in the current version. Please make sure your version is up to date.

**Comment by vancha** [comment]
I've closed the pull request since this seems fixed. I'll close this issue too.
